// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://wefngbhjyxiavjkkrgcy.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlZm5nYmhqeXhpYXZqa2tyZ2N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI5MjQzMDgsImV4cCI6MjA0ODUwMDMwOH0.1V-QmcbKFHJNYZc9SUGKe4iYCBdBMp59S5Uq-PliwJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);